"""
Django settings for app_03 project.

Generated by 'django-admin startproject' using Django 4.1.

For more informa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tion on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/
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
For the full list of settings and their values, see
https://docs.djangoprimport dj_database_url
oject.com/en/4.1/ref/settiht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tps://cloud.digitalocean.com/droplets/315231183/ngs/
"""


from pathlib import Path
from django.contrib.messages import constants as messages
import os
import sys
import dj_database_url



MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}



# Build paths inside th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e project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'enter-your-app-secret-key-here-a-super-long-super-hard-to-guess-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['apps-03-3b3ea.ondigitalocean.app']
#ALLOWED_HOSTS = ['apps-03-3b3ea.ondigitalocean.app', '165.227.94.82']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps03'
 #   'apps-03-3b3ea.ondigitalocean.app',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app_03.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]





WSGI_APPLICATION = 'app_03.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"

#
#DATABASES = {
# 'default': {
#  'ENGINE'  : 'django.db.backends.mysql', # <-- UPDATED line 
#  'NAME'    : 'defaultdb',                 # <-- UPDATED line 
#  'USER'    : 'doadmin',                     # <-- UPDATED line
#  'PASSWORD': 'AVNS_opSyNyIDAt49SbpzqG_',              # <-- UPDATED
#  'HOST'    : 'db-mysql-nyc3-16778-do-user-11647348-0.b.db.ondigitalocean.com',                # <
#  'PORT'    : '25060',
# }
#}

DATABASES = {
    'default': {
        'ENGINE'  : 'django.db.backends.mysql', # <-- UPDATED line 
        'NAME'    : 'dbapps03',                 # <-- UPDATED line 
        'USER'    : 'root',                     # <-- UPDATED line
        'PASSWORD': '',              # <-- UPDATED line
        'HOST'    : 'localhost',                # <-- UPDATED line
        'PORT'    : '3306',
    }
}




#DATABASES = {
 #   'default': {
  #      'ENGINE'  : 'django.db.backends.mysql', # <-- UPDATED line 
   #     'NAME'    : 'dbapps03',                 # <-- UPDATED line 
   #     'USER'    : 'root@droplet-01',                     # <-- UPDATED line
  #      'PASSWORD': '',              # <-- UPDATED line
     #   'HOST'    : 'apps-03-3b3ea.ondigitalocean.app',                
   #     'PORT'    : '3306',
    #     'ENGINE'  : 'django.db.backends.mysql', # <-- UPDATED line 
    #     'NAME'    : 'defaultdb',                 # <-- UPDATED line 
     #    'USER'    : 'doadmin',                     # <-- UPDATED line
     #    'PASSWORD': 'AVNS_opSyNyIDAt49SbpzqG_',              # <-- UPDATED
     #   'HOST'    : 'db-mysql-nyc3-16778-do-user-11647348-0.b.db.ondigitalocean.com',         
    #     'PORT'    : '25060',

        
        
        
        
  #  }
#}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')

CSS_LOCATION = os.path.join(BASE_DIR,'static')


#Dynamic files and documents
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/uploads/'

LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# SMTP Configure
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = ''
