# Generated by Django 4.0.6 on 2022-07-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=9)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=9)),
                ('other', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('occupants', models.PositiveSmallIntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaccom0.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=9)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=9)),
                ('other', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(max_length=10)),
                ('due_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaccom0.duepayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='duepayment',
            name='rental_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaccom0.rentalunit'),
        ),
    ]
